# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-Go-GoPair
version:      1.001
version_from: 
installdirs:  site
requires:
    Algorithm::Pair::Best:         1
    Digest::SHA1:                  0
    Games::Go::AGATourn:           1
    Tk:                            804

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
